# Generated by Django 3.1.1 on 2020-09-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamename', models.CharField(max_length=12, unique=True)),
                ('round', models.IntegerField(default=0, help_text='게임 진행 라운드')),
                ('ingameYn', models.BooleanField(default=False)),
                ('lastCard', models.IntegerField(default=0, help_text='오픈 카드')),
                ('lastCardCnt', models.IntegerField(default=0, help_text='오픈 카드 개수')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('delYn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='계급')),
                ('cardTotCnt', models.IntegerField(default=0, help_text='보유 카드 총 개수')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalmuti.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalmuti.user')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='turnUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalmuti.user'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.IntegerField(default=0, help_text='보유 카드')),
                ('cardCnt', models.IntegerField(default=0, help_text='보유 카드 개수')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalmuti.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalmuti.user')),
            ],
        ),
    ]
