# Generated by Django 3.1.1 on 2020-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardCnt',
            field=models.IntegerField(default=1, help_text='보유 카드 개수'),
        ),
    ]
