# Generated by Django 3.1.1 on 2020-09-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0002_auto_20200917_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardCnt',
        ),
    ]
