# Generated by Django 3.1.1 on 2020-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0003_remove_card_cardcnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ingameYn',
        ),
        migrations.AddField(
            model_name='game',
            name='ingameCd',
            field=models.BooleanField(default=0, help_text='0:게임대기, 1:게임준비, 3:게임중, 4:게임종료'),
        ),
    ]
