# Generated by Django 3.1.1 on 2020-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0005_auto_20200917_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='status',
            field=models.IntegerField(default=0, help_text='0:게임대기, 1:카드확인, 2:게임중, 3:게임종료, 9:레볼루션가능'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ingameCd',
            field=models.IntegerField(default=0, help_text='0:게임대기, 1:게임준비, 2:게임중, 3:게임종료'),
        ),
    ]
