# Generated by Django 3.1.1 on 2020-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0006_auto_20200917_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='status',
        ),
        migrations.AddField(
            model_name='gamer',
            name='jokerCnt',
            field=models.IntegerField(default=0, help_text='조커 카드 개수'),
        ),
    ]
