# Generated by Django 3.1.1 on 2020-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0007_auto_20200917_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='status',
            field=models.IntegerField(default=0, help_text='0:게임대기, 1:조공대기, 2:게임중'),
        ),
    ]
