# Generated by Django 3.1.1 on 2020-09-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0009_gamer_taxyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ingameCd',
            field=models.IntegerField(default=0, help_text='0:게임대기, 1:게임준비, 2:조공대기, 3:게임중, 4:게임종료'),
        ),
    ]
