# Generated by Django 3.1.1 on 2020-09-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0010_auto_20200921_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='revolutionYn',
            field=models.BooleanField(default=False),
        ),
    ]
