# Generated by Django 3.1.1 on 2020-09-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0011_game_revolutionyn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='revolutionYn',
            new_name='revYn',
        ),
    ]
