# Generated by Django 3.1.1 on 2020-09-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0012_auto_20200921_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='revusername',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
