# Generated by Django 3.1.1 on 2020-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0013_game_revusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='revusername',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
