# Generated by Django 3.1.1 on 2020-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0014_auto_20200921_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='nextPosition',
            field=models.IntegerField(default=0, help_text='다음계급'),
        ),
    ]
