# Generated by Django 3.1.1 on 2020-09-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0015_gamer_nextposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lastJokerCnt',
            field=models.IntegerField(default=0, help_text='오픈 조커 개수'),
        ),
    ]
