# Generated by Django 3.1.1 on 2020-09-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0016_game_lastjokercnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lastTotCardCnt',
            field=models.IntegerField(default=0, help_text='오픈 카드 총 개수'),
        ),
    ]
