# Generated by Django 3.1.1 on 2020-09-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0017_game_lasttotcardcnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='lastTotCardCnt',
        ),
    ]
