# Generated by Django 3.1.1 on 2020-09-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalmuti', '0018_remove_game_lasttotcardcnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='drawusername',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='revusername',
            field=models.CharField(default='', max_length=10),
        ),
    ]
